In [13]:
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import accuracy_score,f1_score,roc_auc_score,precision_recall_curve

In [14]:
df=pd.read_csv(r'dataset/dataset_ciprofloxacin_final.csv')

In [15]:
df

,Ciprofloxacin_Resistance,Gene_mdsA,Gene_mdsB,Gene_aph(3'')-Ib,Gene_aph(6)-Id,Gene_tet(A),Gene_tet(B),Gene_fosA7,Gene_aph(3')-IIa,Gene_aph(6)-Ic,Gene_ble,Gene_aac(3)-VIa,Gene_aadA1,Gene_sul1,Gene_fosA7.2,Gene_blaCMY-2,Gene_blaCMY,Gene_sul2,Gene_blaTEM-1,Gene_aadA2,Gene_aph(3')-Ia,Gene_blaCARB-2,Gene_floR,Gene_tet(G),Gene_mcr-9.1,Gene_ant(2'')-Ia,Gene_gyrA_S83F,Gene_ramR_T18P,Gene_dfrA12,Gene_aadA22,Gene_ramR_T50P,Gene_grdA,Gene_tet(C),Gene_aac(3)-IVa,Gene_aph(4)-Ia,Gene_blaTEM,Gene_aadA7,Gene_aadA5,Gene_dfrA17,Gene_fosA7.3,...,Gene_dfrA31,Gene_qnrVC6,Gene_dfrA46,Gene_blaACT-44,Gene_blaACT-56,Gene_blaACT-214,Gene_blaACT-65,Gene_blaACT-35,Gene_blaACT-27,Gene_blaACT-115,Gene_blaACT-41,Gene_aac(6')-Ib-cr7,Gene_blaPER-2,Gene_aac(3)-IIb,Gene_blaFOX-3,Gene_blaACT-3,Gene_qnrE7,Gene_qnrE,Gene_blaACT-1,Gene_blaACT-57,Gene_blaIMI-16,Gene_blaACT-52,Gene_blaACT-143,Gene_blaACT-51,Gene_blaACT-102,Gene_blaACT-28,Gene_blaNMC-A,Gene_blaACT-166,Gene_fosA2,Gene_qnrE3,Gene_blaACT-49,Gene_blaMIR-9,Gene_blaMIR-21,Gene_blaMIR-3,Gene_blaMIR,Gene_blaMIR-12,Gene_blaMIR-27,Gene_blaMIR-20,Gene_blaMIR-28,Gene_blaMIR-22
0,0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26980,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
26981,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
26982,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,

In [16]:
X=df.iloc[:,1:]

In [17]:
y=df.iloc[:,0]

In [18]:
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=42)

In [19]:
from sklearn.model_selection import RandomizedSearchCV
rf=ExtraTreesClassifier(random_state=42)
rf_params = {
    "n_estimators": [50, 100, 200, 300, 400, 500],
    "max_depth": [None, 5,10,20, 40,60],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4,10],
    "max_features": ["sqrt", "log2"],
    "bootstrap": [True]
}
search = RandomizedSearchCV(
    rf,
    rf_params,
    n_iter=20,
    refit="accuracy",
    n_jobs=-1,
    cv=5,
    scoring=['accuracy', 'f1', 'roc_auc','recall'],
)

a=search.fit(X_train, y_train)
a

RandomizedSearchCV(cv=5, estimator=ExtraTreesClassifier(random_state=42),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'bootstrap': [True],
                                        'max_depth': [None, 5, 10, 20, 40, 60],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4, 10],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [50, 100, 200, 300, 400,
                                                         500]},
                   refit='accuracy',
                   scoring=['accuracy', 'f1', 'roc_auc', 'recall'])

In [21]:
et=ExtraTreesClassifier(bootstrap=True,max_depth=60,random_state=42,class_weight='balanced')

In [22]:
et.fit(X_train,y_train)
y_pred=et.predict(X_test)

In [23]:
accuracy_score(y_pred,y_test)

0.9666481378543635

In [24]:
f1_score(y_pred,y_test)

0.9248747913188647

In [25]:
roc_auc_score(y_pred,y_test)

np.float64(0.9547275812593675)

In [26]:
precision_recall_curve(y_pred,y_test)

(array([0.219937  , 0.91645988, 1.        ]),
 array([1.        , 0.93344566, 0.        ]),
 array([0, 1]))